# @package _global_
extract:
#   repro: false
  name: textract
  input_document_s3_bucket:
  feature_types: ["TABLES"]  # allowed ["TABLES", "FORMS", "QUERIES", "SIGNATURES", "LAYOUT"]
  output_dir: data
  target_state: texas
  hf_dataset:
    name: ${extract.name}-${extract.target_state}
    publish_dataset: false
    private: true
  embedding:
    embedding_model: text-embedding-ada-002
