defaults:
  - _self_

global_config:
  experiment_name: textract_es_vanilla_llm
  target_state: connecticut
  eval_terms: ["min_lot_size"] #, "min_unit_size", "max_height"] # all available eval terms ['floor_to_area_ratio', 'max_height', 'max_lot_coverage', 'max_lot_coverage_pavement', 'min_lot_size', 'min_parking_spaces', 'min_unit_size']

  target_town_file: ${global_config.data_output_dir}/target_towns_names.json
  target_district_file: ${global_config.data_output_dir}/target_districts_names.json
  target_eval_file: ${global_config.data_output_dir}/target_eval_data.json
  ground_truth_file: ${global_config.data_output_dir}/ground_truth.json
  thesaurus_file: data/thesaurus.json

  data_output_dir: data/${global_config.target_state} # helper variable, just used to parse
  result_output_dir: results/${global_config.target_state}/${global_config.experiment_name} # helper variable, just used to parse

  pdf_dir: ${global_config.data_output_dir}/pdfs
  ocr_dir: ${global_config.data_output_dir}/ocr
  format_ocr_dir: ${global_config.data_output_dir}/format_ocr
  index_dir: ${global_config.data_output_dir}/index
  search_dir: ${global_config.data_output_dir}/search
  llm_dir: ${global_config.data_output_dir}/llm
  normalization_dir: ${global_config.data_output_dir}/normalization
  eval_dir: ${global_config.data_output_dir}/eval


  es_endpoint: http://localhost:9200

  random_seed: 13
  test_size_per_term: 30


ocr_config:
  method: textract
  run_ocr: false
  input_document_s3_bucket:
  pdf_name_prefix_in_s3_bucket: zoning/${global_config.target_state}/
  feature_types: ["TABLES"]  # allowed ["TABLES", "FORMS", "QUERIES", "SIGNATURES", "LAYOUT"]

format_ocr_config:
  temp: x

index_config:
  method: keyword # allowed keyword/embedding
  index_key: town
  es_endpoint: ${global_config.es_endpoint}
  index_range: 5

search_config:
  method: ${index_config.method}
  es_endpoint: ${global_config.es_endpoint}
  num_results: 5
  is_district_fuzzy: false
  is_eval_term_fuzzy: false
  thesaurus_file: ${global_config.thesaurus_file}

llm_config:
  method: vanilla
  llm_name: gpt-4-1106-preview
  max_tokens: 256
  formatted_response: false
  cache_dir: .diskcache
  templates_dir: zoning/llm/templates
  thesaurus_file: ${global_config.thesaurus_file}

normalization_config:
  method: todo

eval_config:
  template_dir: zoning/eval/templates

hydra:
  run:
    dir: ./hydra_outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
