# @package _global_
defaults:
  - base
  - _self_

global_config:
  experiment_name: textract_es_gpt4_north_carolina_search_range_3
  target_state: north_carolina
  eval_terms: ['floor_to_area_ratio', 'max_height', 'max_lot_coverage', 'max_lot_coverage_pavement', 'min_lot_size', 'min_parking_spaces', 'min_unit_size']


ocr_config:
  run_ocr: true

district_extraction_config:
  run_district_extraction: false

index_config:
  index_range: 3

search_config:
  num_results: 5
  is_district_fuzzy: false
  is_eval_term_fuzzy: false
  preprocess_search_target: false
